version: "3"
services:

  db:
    image: postgres
    container_name: postgresql_metabase
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: db_password
      # PGDATA: /var/lib/postgresql/data
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./db_data:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: db_password
      MB_DB_HOST: db
    depends_on:
      - db